### ISSUE TITLE
Exception on load

### ISSUE THREAD

**Issue by joallard** [DylanPiercey/set-dom#18]
If I include `https://unpkg.com/set-dom@7.2.0/dist/set-dom.js` on a page, I get this error on load:

```
Uncaught DOMException: Failed to execute 'selectNode' on 'Range': the given Node has no parent.
    at Object.r.2 (https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:2727)
    at o (https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:549)
    at https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:600
    at Object.r.1.2 (https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:2535)
    at o (https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:549)
    at e (https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:716)
    at https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:733
    at https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:273
    at https://unpkg.com/set-dom@7.2.0/dist/set-dom.js:1:278
```

Latest Chrome

**Comment by DylanPiercey** [comment]
@joallard thanks for pointing this out. Looks like there was an issue with the build (I really should add a prepublish hook).

Anyways I just released a patch for IE9 and this is also resolved. Try using https://unpkg.com/set-dom@7.3.0/dist/set-dom.js

Let me know if you have any other issues!

**Comment by joallard** [comment]
Thanks! Super quick
